### ISSUE TITLE
Removes convergence in S

### ISSUE THREAD

**Issue by fogus** [benfle/machine-learning#1]
I realize that this codebase was a learning exercise but I came across it and had a great time studying your implementation. The line below seems to eliminate the contents of S when examples cause S & G to converge. 

https://github.com/benfle/machine-learning/blob/d27dc06bb994ae783d9fe827c2f39c18b4cafc37/src/com/benfle/machine_learning/concept.clj#L143

For instance, the example at http://www2.cs.uregina.ca/~dbd/cs831/notes/ml/vspace/vs_prob1.html should result in S = G but after execution I see `#{}` =/= `#{[Japan ? ? ? Economy]}`.

I haven't read Mitchell's "Machine Learning" so I may have missed nuances in his explanation of Concept Space and if so please ignore this. Thank you for sharing this code -- as I would have expected, it's lovely.

**Comment by benfle** [comment]
Thanks for the report. You're right, the `more-general?` predicate here should not be strict otherwise you exclude the hypothesis when the two boundary sets converge. I pushed a fix and added the example from your link. Thanks. It was fun to get back to this :)

**Comment by fogus** [comment]
Excellent! Thank you for indulging me and for putting this into the world. As a fun test I ran `[[:sunny  :warm :normal :strong :cool :change true ] [:cloudy :warm :normal :strong :cool :change true ] [:rainy  :warm :normal :strong :cool :change false]]` through `candidate-elimination` and the version space collapsed as expected!
